# ============================================
# Nacos 配置中心 - 用户服务专属配置
# Data ID: murder-user.yml
# Group: DEFAULT_GROUP
# ============================================

server:
  port: 8082

spring:
  redis:
    database: 0  # 用户服务使用 Redis DB0

# Springdoc 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 日志配置
logging:
  level:
    com.murder.user: debug
